# UFC - Gather env values for VPS Docker + GitHub Secrets
# Run from UnitedFamilyCaregivers folder. Creates docker/.env from ai-gateway/.env
# and outputs GitHub Secrets checklist.

$ErrorActionPreference = "Stop"
$root = Split-Path $PSScriptRoot -Parent

function Get-EnvValue($path, $key) {
    if (-not (Test-Path $path)) { return $null }
    $line = Get-Content $path | Where-Object { $_ -match "^$key=" } | Select-Object -First 1
    if ($line) {
        $v = ($line -split "=", 2)[1]
        if ($v) { return $v.Trim().Trim('"').Trim("'") }
    }
    return $null
}

Write-Host "`n=== UFC Deploy Config Gatherer ===" -ForegroundColor Cyan

# Source: ai-gateway/.env
$aiEnv = Join-Path $root "ai-gateway\.env"
$dockerEnv = Join-Path $root "docker\.env"
$dockerExample = Join-Path $root "docker\.env.example"

if (-not (Test-Path $aiEnv)) {
    Write-Host "[FAIL] ai-gateway/.env not found. Create it from ai-gateway/.env.example" -ForegroundColor Red
    exit 1
}

# Parse ai-gateway .env
$envVars = @{}
Get-Content $aiEnv | ForEach-Object {
    if ($_ -match "^([^#][^=]+)=(.*)$") {
        $envVars[$matches[1].Trim()] = $matches[2].Trim().Trim('"').Trim("'")
    }
}

# Build docker .env (OLLAMA_URL overridden for Docker)
$dockerContent = @"
# UFC AI Gateway - Docker Compose (auto-generated by gather-env-for-deploy.ps1)
PORT=7501
OLLAMA_URL=http://ollama:11434
OLLAMA_MODEL_FAST=$($envVars["OLLAMA_MODEL_FAST"] ?? $envVars["OLLAMA_MODEL"] ?? "llama3.2:3b")
OLLAMA_MODEL_SMART=$($envVars["OLLAMA_MODEL_SMART"] ?? "llama3.3")

SUPABASE_URL=$($envVars["SUPABASE_URL"])
SUPABASE_ANON_KEY=$($envVars["SUPABASE_ANON_KEY"])
LIVEKIT_API_KEY=$($envVars["LIVEKIT_API_KEY"])
LIVEKIT_API_SECRET=$($envVars["LIVEKIT_API_SECRET"])

NEVADA_MEDICAID_USER_ID=$($envVars["NEVADA_MEDICAID_USER_ID"] ?? "")
NEVADA_MEDICAID_PASSWORD=$($envVars["NEVADA_MEDICAID_PASSWORD"] ?? "")
NEVADA_MEDICAID_TOTP_SECRET=$($envVars["NEVADA_MEDICAID_TOTP_SECRET"] ?? "")
"@

$dockerDir = Join-Path $root "docker"
if (-not (Test-Path $dockerDir)) { New-Item -ItemType Directory -Path $dockerDir -Force | Out-Null }
$dockerContent | Out-File -FilePath $dockerEnv -Encoding utf8 -Force
Write-Host "[OK] Created docker/.env from ai-gateway/.env" -ForegroundColor Green

# GitHub Secrets checklist
$envLocal = Join-Path $root ".env.local"
$supabaseUrl = Get-EnvValue $envLocal "NEXT_PUBLIC_SUPABASE_URL"
$supabaseKey = Get-EnvValue $envLocal "NEXT_PUBLIC_SUPABASE_ANON_KEY"
$livekitUrl = Get-EnvValue $envLocal "NEXT_PUBLIC_LIVEKIT_URL"

Write-Host "`n=== GitHub Secrets (Repo > Settings > Secrets and variables > Actions) ===" -ForegroundColor Cyan
Write-Host "Set these - values from .env.local and ai-gateway/.env:" -ForegroundColor Gray
Write-Host ""
Write-Host "  NEXT_PUBLIC_SUPABASE_URL     = $supabaseUrl" -ForegroundColor White
Write-Host "  NEXT_PUBLIC_SUPABASE_ANON_KEY = (from .env.local - paste full anon key)" -ForegroundColor White
Write-Host "  NEXT_PUBLIC_LIVEKIT_URL      = $livekitUrl" -ForegroundColor White
Write-Host "  NEXT_PUBLIC_API_BASE         = https://api.unitedfamilycaregivers.com" -ForegroundColor White
Write-Host ""
Write-Host "After VPS is live and DNS points api -> VPS IP." -ForegroundColor Gray
Write-Host ""

# Summary
Write-Host "=== Summary ===" -ForegroundColor Cyan
Write-Host "  docker/.env: ready (Supabase, LiveKit from ai-gateway/.env)" -ForegroundColor Green
Write-Host "  GitHub: set 4 secrets above, then push to trigger Pages rebuild" -ForegroundColor Green
Write-Host ""
